import type { Product } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "control-total",
    name: "Control Total: Sistema Contable & Financiero",
    description: "Sistema contable completo con balance general, estado de resultados, ratios financieros y dashboard ejecutivo.",
    features: ["Balance General automático", "Estado de Resultados", "Ratios de liquidez y rentabilidad", "Dashboard ejecutivo web", "Exportación PDF", "Flujo de caja 24 meses incluido"],
    price_once: 44990,
    price_monthly: 40491,
    category: "finanzas",
    icon: "shield-check",
    is_active: true,
    sort_order: 1,
  },
  {
    id: "2",
    slug: "flujo-caja-premium",
    name: "Flujo de Caja | Dashboard 360°",
    description: "Control integral de cashflow, gastos, créditos y activos con dashboard web y +20 KPIs automáticos.",
    features: ["CashFlow integrado", "Control de gastos por categoría", "Gestión de créditos", "Control de activos", "20+ KPIs automáticos", "Dashboard web interactivo"],
    price_once: 29990,
    price_monthly: 26991,
    category: "finanzas",
    icon: "trending-up",
    is_active: true,
    sort_order: 2,
  },
  {
    id: "3",
    slug: "flujo-caja-profesional",
    name: "Flujo de Caja Empresarial Profesional",
    description: "Proyección y control de flujo de caja con análisis de tendencias y alertas automáticas.",
    features: ["Proyección a 12 meses", "Análisis de tendencias", "Alertas de liquidez", "Categorización automática", "Reportes mensuales"],
    price_once: 19990,
    price_monthly: 17991,
    category: "finanzas",
    icon: "bar-chart-3",
    is_active: true,
    sort_order: 3,
  },
  {
    id: "4",
    slug: "guia-finanzas",
    name: "Guía Contabilidad y Finanzas para Dueños de Negocios",
    description: "Guía completa para entender y gestionar la contabilidad y finanzas sin ser contador.",
    features: ["Fundamentos contables", "Interpretación de estados financieros", "Gestión tributaria básica", "Indicadores clave", "Casos prácticos Chile"],
    price_once: 19990,
    price_monthly: 17991,
    category: "educacion",
    icon: "book-open",
    is_active: true,
    sort_order: 4,
  },
  {
    id: "5",
    slug: "sesion-estrategica",
    name: "Sesión Estratégica 1:1 con Ingeniero en Finanzas",
    description: "60 minutos con un especialista para resolver dudas financieras y definir estrategia.",
    features: ["60 minutos de consultoría", "Análisis situación actual", "Plan de acción personalizado", "Seguimiento por email", "Grabación de la sesión"],
    price_once: 29990,
    price_monthly: 26991,
    category: "consultoria",
    icon: "users",
    is_active: true,
    sort_order: 5,
  },
  {
    id: "6",
    slug: "evaluacion-creditos",
    name: "Sistema de Evaluación de Créditos",
    description: "Scoring crediticio automatizado con análisis de riesgo para clientes y proveedores.",
    features: ["Scoring crediticio automático", "Análisis de riesgo", "Historial de evaluaciones", "Reportes de decisión", "Integración datos SII"],
    price_once: 39990,
    price_monthly: 35991,
    category: "finanzas",
    icon: "credit-card",
    is_active: true,
    sort_order: 6,
  },
  {
    id: "7",
    slug: "gestion-saas",
    name: "Sistema de Gestión Financiera para SaaS",
    description: "Métricas específicas para SaaS: MRR, ARR, Churn, LTV, CAC y unit economics.",
    features: ["MRR/ARR tracking", "Churn analysis", "LTV y CAC", "Unit economics", "Cohort analysis", "Revenue forecasting"],
    price_once: 29990,
    price_monthly: 26991,
    category: "finanzas",
    icon: "cloud",
    is_active: true,
    sort_order: 7,
  },
  {
    id: "8",
    slug: "ordenes-compra",
    name: "Sistema de Órdenes de Compra",
    description: "Gestión de órdenes de compra con aprobaciones, seguimiento y control presupuestario.",
    features: ["Generación OC automática", "Flujo de aprobaciones", "Control presupuestario", "Seguimiento entregas", "Historial proveedores"],
    price_once: 19900,
    price_monthly: 17910,
    category: "operaciones",
    icon: "shopping-cart",
    is_active: true,
    sort_order: 8,
  },
  {
    id: "9",
    slug: "presupuestos",
    name: "Sistema de Presupuestos Profesionales",
    description: "Presupuestos profesionales con plantillas personalizables, seguimiento y conversión a factura.",
    features: ["Plantillas personalizables", "Cálculo automático IVA", "Seguimiento de estado", "Conversión a factura", "Reportes de conversión"],
    price_once: 39990,
    price_monthly: 35991,
    category: "finanzas",
    icon: "file-text",
    is_active: true,
    sort_order: 9,
  },
];
